title: Joe Spence
logo: /assets/img/IMG-20210821-WA0022_v2.jpg
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <a href="https://www.linkedin.com/in/joseph-spence-b4503955/">View my LinkedIn Profile</a>
#show_downloads: true
theme: jekyll-theme-minimal
github:
  is_project_page: false
